# module reflections du chatBot umapon

my_reflections = {
    "je suis":"tu es",
    "tu es":"je suis",
    "j'etais":"tu etais",
    "tu etais":"j'etais",
    "moi":"toi",
    "mon":"ton",
    "je":"tu",
    "je voulais":"tu voulais",
    "tu voulais":"je voulais",
    "tu":"je",
    "ton":"mon",
    "toi":"moi",
    "nous":"vous",
    "vous":"nous",
    "j'ai":"tu as",
    "tu as":"j'ai",
    "je veux":"tu veux",
    "tu veux":"je veux",
    "je peux":"tu peux",
    "tu peux":"je peux",
    "notre":"votre",
    "votre":"notre",
    "vos":"nos",
    "nos":"vos",
    "me":"te",
    "te":"me"
}